### ISSUE TITLE
Grid column's field visible and format options

### ISSUE THREAD

**Issue by georges49** [shieldui/shieldui-lite#7]
https://www.shieldui.com/documentation/grid/javascript/api/settings/columns/visible
https://www.shieldui.com/documentation/grid/javascript/api/settings/columns/format

I tried to use the visible option like this { field: "ID", visible: false } but the column still appear.
I also tried to use the format option to change the format of a column that has Date as type but it did not work.

**Comment by shieldui** [comment]
The column visibility is not included in shieldui-lite, only in the full Shield UI library, available on the website.

How is the format not working - can you be more specific and provide a JSBin example?

**Comment by georges49** [comment]
Here's an example:
https://codepen.io/SitePoint/pen/VvZeKd/

The library is this: //s3-us-west-2.amazonaws.com/s.cdpn.io/123941/shield-ui-lite.js

As you can see the date of birth column has 
**format: "{0:MM/dd/yyyy}"**

But the date appears in different format

**Comment by georges49** [comment]
The hideColumn method does not work?
https://www.shieldui.com/documentation/grid/javascript/api/methods/hideColumn
I tried to use it instead of visible:false

**Comment by shieldui** [comment]
hideColumn() is not in shieldui-lite either:
https://github.com/shieldui/shieldui-lite/blob/master/grid/js/grid.js - cannot be found here

And I will forward the issue for the format to the developers.

**Comment by daedrics** [comment]
How can you select the text in shiueld ui grid? Is there any property for doing that? Because I cant select it for copying purposes.

**Comment by shieldui** [comment]
You should be able to allow selection by adding a few CSS properties to override the default behavior.

**Comment by shieldui** [comment]
Check this demo: http://demos.shieldui.com/web/grid-general/text-selection

**Comment by VNGlushchenko** [comment]
> Here's an example:
> https://codepen.io/SitePoint/pen/VvZeKd/
> 
> The library is this: //s3-us-west-2.amazonaws.com/s.cdpn.io/123941/shield-ui-lite.js
> 
> As you can see the date of birth column has
> format: "{0:MM/dd/yyyy}"
> 
> But the date appears in different format

I have the same problem with date format. 

You wrote:
> "And I will forward the issue for the format to the developers." 

Has this problem been fixed?

**Comment by adhayward** [comment]
So I was encountering this problem too and after extensive debugging found the problem and thought I would leave my findings here to help anyone else in future.

The main shield-ui includes another library, [globalizejs/globalize](https://github.com/globalizejs/globalize), directly in it's own minified JS file but the lite version only specifies it as a dependency so it will need to be included separately - this isn't made hugely obvious if you're looking at the demos and documentation on shieldui.com like I definitely did and @georges49 and @VNGlushchenko appear to be doing too.

All of the formatting used in the shield examples that is done through strings like "{0:d}" is using Globalize's format function internally.

What also doesn't help is that it uses the 0.x version of globalize too which is very different to the current 1.x version **which is not compatible** due to the format function being dropped at version 1.0 in favour of separate functions for different data types.

So the only way to use the formatting as it is in the docs is to include the globalize.min.js file from the 0.1.1 release.
